import {DiVisualstudio, DiDatabase, DiJavascript, DiCss3, DiPython, DiTerminal, DiHtml5} from 'react-icons/di'


export default {
    'javascript' :{
        id: 'javascript',
        text: 'JavaScript',
        icon: DiJavascript,
        color: '#efd81e',
        filter: ['frontEnd', 'backEnd', 'dataBase'],
        progressRatio: .95,
        projects: 3,
        certificates: 23,
    },
    'css' :{
        id: 'css',
        text: 'CSS',
        icon: DiCss3,
        color: '#016bb4',
        filter: ['frontEnd'],
        progressRatio: .9,
        projects: 0,
        certificates: 10,
    },
    'python' :{
        id: 'python',
        text: 'Python',
        icon: DiPython,
        color: '#01d638',
        filter: ['backEnd'],
        progressRatio: .3,
        projects: 1,
        certificates: 2,
    },
    'bash' :{
        id: 'bash',
        text: 'Bash',
        icon: DiTerminal,
        color: '#eaeaeb',
        filter: ['infraStructure'],
        progressRatio: .25,
        projects: 3,
        certificates: 5,
    },
    'csharp' :{
        id: 'csharp',
        text: 'C Sharp',
        icon: DiVisualstudio,
        color: '#7d3583',
        filter: ['backEnd'],
        progressRatio: .5,
        projects: 9,
        certificates: 2,
    },'vb' :{
        id: 'vb',
        text: 'Visual Basic',
        icon: DiVisualstudio,
        color: '#185c91',
        filter: ['backEnd'],
        progressRatio: .4,
        projects: 1,
        certificates: 3,
    },
    'html' :{
        id: 'html',
        text: 'HTML',
        icon: DiHtml5,
        color: '#e34d26', 
        filter: ['frontEnd'],
        progressRatio: .9,
        projects: 5,
        certificates: 12,
    },
    'sql' :{
        id: 'sql',
        text: 'SQL',
        icon: DiDatabase,
        color: '#f84741',
        filter: ['dataBase'],
        progressRatio: .87,
        projects: 3,
        certificates: 1,
    },
    
}